### ISSUE TITLE
Incorrect RSS links

### ISSUE THREAD

**Issue by dbertram** [yusukebe/yusu.ke#2]
Just a couple of follow-ups to #1:

1. In https://blog.yusu.ke/rss.xml the links to individual items have the wrong path. For example, the latest post as of today links to `https://blog.yusu.ke/blog/workers-tech-talks-5/` (note the extra `/blog/` path segment), while that post actually lives at `https://blog.yusu.ke/workers-tech-talks-5/`

2. Potentially related, if you view the source of a post such as `https://blog.yusu.ke/workers-tech-talks-5/`, the `<link rel="alternate">` points to `https://blog.yusu.ke/workers-tech-talks-5/rss.xml`, which doesn't exist. The RSS feed only appears to live at `https://blog.yusu.ke/rss.xml`

**Comment by yusukebe** [comment]
Hi @dbertram 

Thank you for the report. I think it was fixed. Can you check it?

**Comment by dbertram** [comment]
The main rss feed links are correct now (1 above), but the `<link rel="alternate">` on individual blog posts is still incorrect (see 2 above).

**Comment by yusukebe** [comment]
@dbertram 

Sorry, I missed it. The issue was fixed!

**Comment by dbertram** [comment]
Everything looks good now! 👍
